# Starship Prompt Configuration

# Inserts a blank line between shell prompts
add_newline = true
# Configuration for the prompt format
format = """
[╭─](bold bg:none fg:bright-green)[](fg:#65737E)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$time\
[](fg:#464347)\
$line_break\
$character
"""

# Timeout for scanning files in the directory (milliseconds)
scan_timeout = 20


# Configuration for the OS module
[os]
format = "[(bg:#65737E fg:#464347)$symbol[](bg:#464347 fg:#65737E)]($style)"
style = "bg:#65737E fg:#EEEEEE"
disabled = false

# Custom symbols for various operating systems
# This is the default symbols table.
[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = " "
Illumos = "󰈸 "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = "🏴 "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

# Configuration for the username module
[username]
show_always = true
style_root = "bg:#5E81AC  #1B2B34"
style_user = "bg:#5E81AC #eceff4"
format = "[[](bg:#5E81AC fg:#464347)$user[](bg:#464347 fg:#5E81AC)]($style)"

# Configuration for the ROOT module
# [username]
# show_always = true
# style_root = "bg:#bf616a fg:bold #eceff4"
# style_user = "bg:#bf616a fg:bold #eceff4"
# format = "[[](bg:#bf616a fg:#464347)$user[](bg:#464347 fg:#bf616a)]($style)"

# Configuration for the hostname module
[hostname]
ssh_only = false
format = "[[](bg:#81A1C1 fg:#464347)[$ssh_symbol](bold) $hostname(bold red) [](bg:#464347 fg:#81A1C1)]($style)"
style = "bg:#81A1C1 fg:#1B2B34"
disabled = false
ssh_symbol=' '

# Configuration for the directory module
[directory]
style = "bg:#88C0D0 fg:#1B2B34"
read_only = "  "
truncation_length = 3
truncation_symbol = "…/"
format = "[[](bg:#88C0D0 fg:#464347)$path$read_only[](bg:#464347 fg:#88C0D0)]($style)"

# Custom substitutions for long paths
[directory.substitutions]
"~/Documents" = " "
"~/Music" = " "
"~/Movies" = "󰎁 "
"~/Pictures" = " "
"~/Downloads" = " "
"~/Sources" = ""
"~/Documentos" = " "
"~/Música" = " "
"~/Vídeos" = "󰎁 "
"~/Imágenes" = " "
"~/Descargas" = " "
"/git"="GITs "
"~" = " "
#"/" = "  "
# Add more substitutions as needed


##################### DOCKER CONTEXTS ########################
[docker_context]
symbol = " 🐳 "
style = "bg:#24B7E9 fg:#1B2B34"
format = "[[](bg:#24B7E9 fg:#464347)[$symbol$context][](bg:#464347 fg:#24B7E9)]($style)"

# Configuration for the git branch module
[git_branch]
symbol = "󰊢 "
style = "bg:#FAC863 fg:#1B2B34"
truncation_length = 6
truncation_symbol = ""
# ignore_branches = ["master", "main"]
format = "[[](bg:#FAC863 fg:#464347)( $symbol$branch )]($style)"

[git_commit]


[git_status]
format = "[( )[](bg:#464347 fg:#FAC863)]($style)"

# [aws]
# style = "bg:#FF9900 fg:#1B2B34"
# symbol = ' '
# format = "[[](bg:#FF9900 fg:#464347)on [$symbol($profile )(\($region\) )]($style)[](bg:#464347 fg:#FF9900)]($style)"


# [aws.region_aliases]
# us-east-2='US-OH'
# us-east-1='US-VA'
# us-west-1='US-CA'
# us-west-2='US-OR'
# af-south-1='ZA-CT'
# ap-east-1='HK'
# ap-south-2='IN-TS'
# ap-southeast-3='ID-JK'
# ap-southeast-4='AU-VIC'
# ap-south-1='IN-MH'
# ap-northeast-3='JP-OS'
# ap-northeast-2='KR-SE'
# ap-southeast-1='SG'
# ap-southeast-2='AU-NSW'
# ap-northeast-1='JP-13'
# ca-central-1='US-CENTRAL'
# eu-central-1='DE-HE'
# eu-west-1='IE'
# eu-west-2='UK-ENG'
# eu-south-1='IT-MI'
# eu-west-3='FR-75'
# eu-south-2='ES'
# eu-north-1='SE-SE'
# eu-central-2='CH-ZH'
# il-central-1='IL'
# me-south-1='BH'
# me-central-1='AE'
# sa-east-1='BR-SP'
# us-gov-east-1='US-EASTERN'
# us-gov-west-1='US-WESTERN'

#[azure]
# style = "bg:#088DD7 fg:#ffffff"
# symbol = '☁ '
# format = "[[](bg:#088DD7 fg:#464347)( on [$symbol($username)] )]($style)"


# Configuration for the time module
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#8fbcbb #1B2B34"
format = '[[](fg:#464347 bg:#8fbcbb)🕙$time [](bg:#464347 fg:#8fbcbb)]($style)'


# Configuration for the character module
[character]
success_symbol = "[[╰─](bold bg:none fg:bright-green)](fg:#AFD700)"
error_symbol = "[[╰─](bold bg:none fg:bright-green)(bright-red)](fg:#ff3322)"
vicmd_symbol = "[[╰─](bold bg:none fg:bright-green)(bright-blue)](fg:#ff3322)"
format = "[[](bg:#464347)$symbol ]($style)"
